export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-slate-50">
      <div className="bg-[#0d1b4b] py-12 sm:py-16">
        <div className="max-w-3xl mx-auto px-4 text-center">
          <div className="text-4xl mb-4">📜</div>
          <h1 className="font-display text-3xl sm:text-4xl font-bold text-white mb-3">Terms of Service</h1>
          <p className="text-blue-200/70 text-sm">Last updated: January 2025 · Nithya Stamp AI, Alangulam</p>
        </div>
      </div>

      <div className="max-w-3xl mx-auto px-4 py-10 sm:py-14">
        <div className="bg-white rounded-3xl shadow-sm border border-slate-100 p-6 sm:p-10 space-y-8 text-slate-600 text-sm leading-relaxed">

          <section>
            <h2 className="font-display text-xl font-bold text-[#0d1b4b] mb-3">1. Agreement to Terms</h2>
            <p>By accessing or using Nithya Stamp AI ("Service"), operated by Nithya Press, Alangulam, Tenkasi, Tamil Nadu, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[#0d1b4b] mb-3">2. Service Description</h2>
            <p>Nithya Stamp AI provides an AI-powered platform to design and order custom rubber stamps. Our service includes:</p>
            <ul className="mt-3 space-y-2 list-disc list-inside">
              <li>AI-generated stamp design previews using Claude AI</li>
              <li>Online payment processing via Razorpay</li>
              <li>Manufacturing and delivery of physical rubber stamps</li>
              <li>Order tracking and email notifications</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[#0d1b4b] mb-3">3. Ordering & Payment</h2>
            <ul className="space-y-3">
              <li><strong>Order confirmation:</strong> Orders are confirmed only after successful payment via Razorpay.</li>
              <li><strong>Pricing:</strong> All prices are displayed in Indian Rupees (₹) inclusive of applicable taxes. Prices may change without prior notice.</li>
              <li><strong>Payment:</strong> We accept UPI, credit/debit cards, net banking, and wallets via Razorpay. All transactions are encrypted and secure.</li>
              <li><strong>Order cancellation:</strong> Orders may be cancelled within 2 hours of placing, before production begins. Contact us immediately at nithyapress92@gmail.com.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[#0d1b4b] mb-3">4. Delivery Terms</h2>
            <ul className="space-y-3">
              <li><strong>Delivery time:</strong> 3–7 business days from order confirmation, depending on location within India.</li>
              <li><strong>Delivery area:</strong> We currently deliver across India. Remote areas may take additional time.</li>
              <li><strong>Address accuracy:</strong> You are responsible for providing a correct and complete delivery address. We are not liable for delays due to incorrect addresses.</li>
              <li><strong>Tracking:</strong> You will receive delivery updates via email.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[#0d1b4b] mb-3">5. Acceptable Use</h2>
            <p>You agree NOT to use our service to create stamps that:</p>
            <ul className="mt-3 space-y-2 list-disc list-inside">
              <li>Impersonate government bodies, official seals, or registered trademarks</li>
              <li>Are fraudulent, deceptive, or intended to mislead others</li>
              <li>Violate any laws of India or your jurisdiction</li>
              <li>Infringe on the intellectual property rights of others</li>
            </ul>
            <p className="mt-3">We reserve the right to cancel any order that violates these terms. Legal action may be taken for fraudulent use.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[#0d1b4b] mb-3">6. AI-Generated Designs</h2>
            <p>Stamp designs are generated by AI (Anthropic Claude). While we strive for accuracy, the AI may occasionally produce designs that require minor adjustments. We review designs before production. The final physical stamp may have minor variations from the digital preview due to manufacturing tolerances.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[#0d1b4b] mb-3">7. Limitation of Liability</h2>
            <p>Nithya Stamp AI and Nithya Press shall not be liable for:</p>
            <ul className="mt-3 space-y-2 list-disc list-inside">
              <li>Indirect, incidental, or consequential damages</li>
              <li>Delays caused by courier services beyond our control</li>
              <li>Losses arising from incorrect information provided by the customer</li>
            </ul>
            <p className="mt-3">Our total liability is limited to the amount paid for the specific order in question.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[#0d1b4b] mb-3">8. Governing Law</h2>
            <p>These terms are governed by the laws of India. Any disputes shall be subject to the jurisdiction of courts in Tenkasi, Tamil Nadu, India.</p>
          </section>

          <section>
            <h2 className="font-display text-xl font-bold text-[#0d1b4b] mb-3">9. Contact</h2>
            <div className="bg-slate-50 rounded-2xl p-4 space-y-1">
              <p className="font-semibold text-[#0d1b4b]">Nithya Stamp AI — Nithya Press</p>
              <p>📧 nithyapress92@gmail.com</p>
              <p>📞 +91 95788 20558</p>
              <p>📍 Alangulam, Tenkasi, Tamil Nadu, India</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  )
}
